name: example
description: The example for due_date package.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  due_date:
    path: ../

dev_dependencies:
  lints: ^6.0.0
  very_good_analysis: ^10.0.0
