name: due_date
description: A package for working with repeating DateTime patterns (like the same day every month).
version: 3.0.0
homepage: https://fmorschel.github.io/due_date/
repository: https://github.com/FMorschel/due_date

funding:
  - https://github.com/sponsors/FMorschel
  - https://www.buymeacoffee.com/fmorschel

topics:
  - date
  - datetime
  - date-time
  - time
  - calendar
  #- common-utilities
  #- util
  #- utils

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  clock: ^1.0.0
  collection: ^1.0.0
  equatable: ^2.0.3
  essential_lints_annotations: ^0.1.1
  meta: ^1.0.0
  time: ^2.1.6

dev_dependencies:
  analyzer: ^10.0.0
  frontend_server_client: ^4.0.0 # Test bug https://github.com/dart-lang/test/issues/2516
  intl: any
  lints: ^6.0.0
  path: ^1.9.1
  test: any
  very_good_analysis: ^10.0.0
